# Learning objectives
- Know how to import Python packages in Google Colab
- Understand what a dataframe is in the Pandas package
- Learn to how create and inspect DataFrames
- Understand how to work with the datetime format

# Importing packages

In [1]:
import numpy as np
import pandas as pd

In [37]:
my_random_numbers = np.random.randint(1,10,size=(5,3))
print(my_random_numbers)

[[5 9 5]
 [8 4 4]
 [5 6 3]
 [6 2 3]
 [3 4 7]]


In [38]:
type(my_random_numbers)

numpy.ndarray

# Pandas dataframes

In [41]:
my_data = {
    'name':['Alice','Bob','Carlos'],
    'age':[34, 45, 58],
    'diagnosis-date':['2023-01-03','2023-01-04','2023-01-10']
}
print(my_data)

# Convert this to dataframe
patients = pd.DataFrame(my_data)
print(patients)

{'name': ['Alice', 'Bob', 'Carlos'], 'age': [34, 45, 58], 'diagnosis-date': ['2023-01-03', '2023-01-04', '2023-01-10']}
     name  age diagnosis-date
0   Alice   34     2023-01-03
1     Bob   45     2023-01-04
2  Carlos   58     2023-01-10


In [42]:
type(patients)

pandas.core.frame.DataFrame

# Exploring a DataFrame

In [46]:
patients.head(n=2)

name  age diagnosis-date
0  Alice   34     2023-01-03
1    Bob   45     2023-01-04

In [49]:
patients.columns

Index(['name', 'age', 'diagnosis-date'], dtype='object')

In [50]:
patients.dtypes

name              object
age                int64
diagnosis-date    object
dtype: object

In [52]:
# Summary of the data
patients.describe(include = 'all')

name        age diagnosis-date
count       3   3.000000              3
unique      3        NaN              3
top     Alice        NaN     2023-01-03
freq        1        NaN              1
mean      NaN  45.666667            NaN
std       NaN  12.013881            NaN
min       NaN  34.000000            NaN
25%       NaN  39.500000            NaN
50%       NaN  45.000000            NaN
75%       NaN  51.500000            NaN
max       NaN  58.000000            NaN

In [53]:
# Another Pandas application: dates

In [54]:
patients.head()

name  age diagnosis-date
0   Alice   34     2023-01-03
1     Bob   45     2023-01-04
2  Carlos   58     2023-01-10

In [56]:
# Convert diagnosis date column to DATETIME format
patients['diagnosis-date'] = pd.to_datetime(patients['diagnosis-date'])
patients.dtypes

name                      object
age                        int64
diagnosis-date    datetime64[ns]
dtype: object

In [57]:
# Extract the month
patients['month'] = patients['diagnosis-date'].dt.month
patients.head()

name  age diagnosis-date  month
0   Alice   34     2023-01-03      1
1     Bob   45     2023-01-04      1
2  Carlos   58     2023-01-10      1

In [58]:
# Filter patients diagnosed after Janaury 5th
patients[patients['diagnosis-date'] > '2023-01-05']

name  age diagnosis-date  month
2  Carlos   58     2023-01-10      1