# Lecture 4. Importing Packages, Pandas Basics, and Date Handling

## Learning Objectives

By the end of this lecture, you will:
- Know how to import Python packages in Google Colab
- Understand what a DataFrame is in Pandas
- Learn how to create and inspect DataFrames
- Understand how to work with the datetime format

## ✨ 1. Importing Packages in Google Colab
In Google Colab, most common packages are pre-installed. You can import them into your notebook like this:

In [3]:
import numpy as np
import pandas as pd

In [5]:
# Numpy illustration:
my_random_numbers = np.random.randint(1,10,size=(5,3))
print(my_random_numbers)
type(my_random_numbers)

[[5 2 7]
 [1 3 9]
 [5 9 9]
 [1 2 4]
 [4 4 2]]


numpy.ndarray

## 📃 2. What is a Pandas DataFrame?

In [ ]:
data = {
    'name': ['Alice', 'Bob', 'Carlos'],
    'age': [34, 45, 29],
    'diagnosis_date': ['2023-01-03', '2023-01-04', '2023-01-10']
}

# Convert to DataFrame
patients = pd.DataFrame(data)
patients

## 🔍 3. Exploring a DataFrame

In [ ]:
# Show the first few rows
patients.head()

# Check the column names
patients.columns

# See data types
patients.dtypes

# Get a quick summary
patients.describe(include='all')

## 🕒 4. Working with Dates in Pandas

In [ ]:
# Convert diagnosis_date to datetime format
patients['diagnosis_date'] = pd.to_datetime(patients['diagnosis_date'])
patients.dtypes

In [ ]:
# Extract the month
patients['month'] = patients['diagnosis_date'].dt.month

# Filter patients diagnosed after Jan 5th
patients[patients['diagnosis_date'] > '2023-01-05']

In [ ]:
# Count by date
counts = patients['diagnosis_date'].value_counts().sort_index()

# Plot
plt.figure(figsize=(6,4))
counts.plot(kind='bar')
plt.title('Number of Diagnoses per Day')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

## 🚀 Summary

- Use `import` to load packages; install others with `!pip install`
- Pandas DataFrames store tabular data
- Use `pd.to_datetime()` to parse dates
- Datetime columns allow time filtering and features like month extraction